version: "3.8"


networks:
  webweb:
    ipam:
      config:
      - subnet: 172.16.238.0/24
        gateway: 172.16.238.1


services:
    db:
        image: postgres
        container_name: db
        restart: always
        environment:
          - POSTGRES_HOST=db
          - PORT=5432
          - POSTGRES_DB=chessbase
          - POSTGRES_USER=owner
          - POSTGRES_PASSWORD=harnas 
        ports:
            - "5432:5432"
        networks:
          webweb:
            ipv4_address: "172.16.238.10"
    redis:
        image: redis
        container_name: redis
        restart: always
        ports:
          - "6379:6379"
        networks:
          webweb:
            ipv4_address: "172.16.238.13"
    backend:
        build: ./backend 
        container_name: backend
        restart: on-failure
        environment:
          - EMAIL_HOST_USER= ${EMAIL_HOST_USER}
          - EMAIL_HOST_PASSWORD= ${EMAIL_HOST_PASSWORD}
          - GITHUB_WORKFLOW= ${GITHUB_WORKFLOW}
        volumes:
            - ./backend:/app/backend
        command:  bash -c "python3 manage.py makemigrations && 
                           python3 manage.py migrate &&
                           python3 manage.py runserver 172.16.238.11:8000"
        ports:
            - "8000:8000"
        stdin_open: true
        tty: true
        depends_on:
            - db
        networks:
          webweb:
            ipv4_address: "172.16.238.11"
    frontend:
        build: ./frontend
        container_name: frontend
        volumes:
            - ./frontend:/app
        ports:
            - "3000:3000"
        command: npm start
        depends_on:
            - backend
        networks:
          webweb:
            ipv4_address: "172.16.238.12"
    celery:
        build: ./backend
        container_name: celery
        command: bash -c "celery -A base worker -l INFO"
        volumes:
            - ./backend:/app/backend
        depends_on:
            - db
            - redis
            - backend
        networks:
          webweb:
            ipv4_address: "172.16.238.14"
