version: "3.8"

networks:
  webweb:
    ipam:
      config:
      - subnet: 172.16.238.0/24
        gateway: 172.16.238.1


services:
    db:
        image: postgres
        container_name: db
        restart: always
        environment:
          - POSTGRES_HOST=db
          - PORT=5432
          - POSTGRES_DB=chessbase
          - POSTGRES_USER=owner
          - POSTGRES_PASSWORD=harnas 
        ports:
            - "5432:5432"
        networks:
          webweb:
            ipv4_address: "172.16.238.10"
    backend:
        build: ./backend 
        container_name: backend
        restart: on-failure
        volumes:
            - ./backend:/app/backend
        command:  bash -c "./wait-for.sh db:5432 -- python3 manage.py makemigrations && 
                           python3 manage.py migrate &&
                           python3 manage.py runserver 172.16.238.11:8000"
        ports:
            - "8000:8000"
        stdin_open: true
        tty: true
        depends_on:
            - db
        networks:
          webweb:
            ipv4_address: "172.16.238.11"
    frontend:
        build: ./frontend
        container_name: frontend
        volumes:
            - ./frontend:/app
            - /app/node_modules
        ports:
            - "3000:3000"
        command: npm start
        depends_on:
            - backend
        networks:
          webweb:
            ipv4_address: "172.16.238.12"
