name: Tests

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name : Create network for dockers
      run: docker network create webweb
        
    - name: Run website
      run: docker-compose -f ${{github.workspace}}/docker-compose.yml up -d

    - name: Run tests
      run: |
        docker run  \
        -v ${{github.workspace}}/test/results:/opt/robotframework/reports:Z \
        -v ${{github.workspace}}/test/origin:/opt/robotframework/tests:Z \
        --user=1001:1001 \
        --network=webweb \
        ppodgorsek/robot-framework:latest
        
