name: Tests

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:10.8
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: passwd
          POSTGRES_DB: chessbase
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    
    


    steps:
    - uses: actions/checkout@v1
        
    - name: Run website
      run: docker-compose -f ${{github.workspace}}/docker-compose.yml up -d

    - name: wait for dockers
      uses: jakejarvis/wait-action@master
      with:
        time: '220s'

    - name: check all containers
      run: docker ps

    - name: Run tests
      run: |
        docker run -p 5000:5000 \
          -v ${{github.workspace}}/test/results:/opt/robotframework/reports:Z \
          -v ${{github.workspace}}/test/origin:/opt/robotframework/tests:Z \
          --user=1001:1001 \
          ppodgorsek/robot-framework:latest
